authapp/urls.py
from django.urls import path

import authapp.views

app_name = 'authapp'

urlpatterns = [
    path('', authapp.views.index, name='index'),
    path('login/', authapp.views.login, name='login'),
    path('logout/', authapp.views.logout, name='logout'),
    path('register/', authapp.views.registration, name='register'),
    path('list/', authapp.views.CustomUserList.as_view(), name='users_list'),
    path('update/<int:pk>/', authapp.views.CustomUserUpdate.as_view(), name='users_update'),
]

courseapp/urls.py
from django.urls import path

import courseapp.views

app_name = 'courseapp'

urlpatterns = [
    # path('', authapp.views.index, name='index'),
    path('list/', courseapp.views.CourseList.as_view(), name='course_list'),
    path('settings/', courseapp.views.CourseSettingsList.as_view(), name='course_settings_list'),
    path('add/', courseapp.views.CourseAdd.as_view(), name='course_add'),
    path('<int:pk>/', courseapp.views.CourseItem.as_view(), name='course'),
    path('update/<int:pk>/', courseapp.views.CourseUpdate.as_view(), name='course_update'),
    # path('logout/', authapp.views.logout, name='logout'),
    path('events-list/', courseapp.views.SiteEventsList.as_view(), name='events_list'),
    path('events-settings-list/', courseapp.views.SiteEventsSettingsList.as_view(), name='events_settings_list'),
    path('events/<int:pk>/', courseapp.views.SiteEventsItem.as_view(), name='events'),
    path('events/add/', courseapp.views.SiteEventsAdd.as_view(), name='events_add'),
    path('events/update/<int:pk>/', courseapp.views.SiteEventsUpdate.as_view(), name='events_update'),
    path('relation-settings-list/', courseapp.views.RelationSettingsList.as_view(), name='relation_settings_list'),
]

tutorTellcap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import authapp.views

handler404 = authapp.views.show_404

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', authapp.views.index),
    path('auth/', include('authapp.urls')),
    path('courses/', include('courseapp.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


# Create your models here.

class CustomUser(AbstractUser):
    class Meta:
        verbose_name_plural = 'Пользователи'
        verbose_name = 'Пользователя'

    avatar = models.ImageField(upload_to='Аватар', blank=True)
    birthday = models.DateField(verbose_name='День рождения', blank=True, null=True)
    activate_key = models.CharField(verbose_name='Код активации', max_length=128, blank=True, null=True)
    superintendent = models.BooleanField(verbose_name='Сотрудник', default=False)
    surname = models.CharField(verbose_name='Отчетство', max_length=25, default='', blank=True)
    personal_code = models.CharField(verbose_name='Персональный код', max_length=4, default='', blank=True)

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

    def get_absolute_url(self):
        return reverse('authapp:users_list')

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms

from authapp.models import CustomUser


class UserLoginForm(AuthenticationForm):
    class Meta:
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')


class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = '__all__'

authapp/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_obj
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from authapp.forms import UserLoginForm, SignUpForm, CustomUserUpdateForm
from authapp.models import CustomUser


# Create your views here.


def show_404(request, exception=None):
    return render(request, 'authapp/404.html')


def index(request):
    return render(request, 'authapp/base.html')


def login(request):
    title = ':: TELLCAP :: Авторизация'

    if request.method == 'POST':
        login_form = UserLoginForm(data=request.POST)
        if login_form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('authapp:index'))
    else:
        login_form = UserLoginForm()
    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/base.html', {'form': login_form})


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('courseapp:course_list'))


def registration(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login_obj(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'authapp/base.html', {'form': form})


class CustomUserList(ListView):
    model = CustomUser


class CustomUserUpdate(UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- ** Plugins Needed for the Project ** -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'tutor/plugins/bootstrap/bootstrap.min.css' %}">
    <!-- slick slider -->
    <link rel="stylesheet" href="{% static 'tutor/plugins/slick/slick.css' %}">
    <!-- themefy-icon -->
    <link rel="stylesheet" href="{% static 'tutor/plugins/themify-icons/themify-icons.css' %}">
    <!-- animation css -->
    <link rel="stylesheet" href="{% static 'tutor/plugins/animate/animate.css' %}">
    <!-- aos -->
    <link rel="stylesheet" href="{% static 'tutor/plugins/aos/aos.css' %}">
    <!-- venobox popup -->
    <link rel="stylesheet" href="{% static 'tutor/plugins/venobox/venobox.css' %}">

    <!-- Main Stylesheet -->
    <link href="{% static 'tutor/css/style.css' %}" rel="stylesheet">

    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'tutor/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'tutor/images/favicon.ico' %}" type="image/x-icon">

</head>

<body>
<!-- jQuery -->
<script src="{% static 'tutor/plugins/jQuery/jquery.min.js' %}"></script>

<!-- header -->
<header class="fixed-top header">
    <!-- top header -->
    {% include 'authapp/top_header.html' %}

    <!-- navbar -->
    {% include 'authapp/navbar.html' %}

</header>
<!-- /header -->
<!-- Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content rounded-0 border-0 p-4">
            <div class="modal-header border-0">
                <h3>Register</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="login">
                    <form action="{% url 'authapp:register' %}" class="row" method="post">
                        {% csrf_token %}
                        <div class="col-12">
                            <input type="text" class="form-control mb-3" id="id_username" name="username"
                                   placeholder="Nickname">
                        </div>
                        <div class="col-12">
                            <input type="email" class="form-control mb-3" id="id_email" name="email"
                                   placeholder="Email">
                        </div>
                        <div class="col-12">
                            <input type="password" class="form-control mb-3" id="id_password1" name="password1"
                                   placeholder="Password">
                        </div>
                        <div class="col-12">
                            <input type="password" class="form-control mb-3" id="id_password2" name="password2"
                                   placeholder="Password">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">SIGN UP</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content rounded-0 border-0 p-4">
            <div class="modal-header border-0">
                <h3>Login</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'authapp:login' %}" class="row" method="post">
                    {% csrf_token %}
                    <div class="col-12">
                        <input type="text" class="form-control mb-3" id="id_username" name="username"
                               placeholder="Username">
                    </div>
                    <div class="col-12">
                        <input type="password" class="form-control mb-3" id="id_password" name="password"
                               placeholder="Password">
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">LOGIN</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% block slider %}
    <div id="myModal" class="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтверждение</h5>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>
                <div class="modal-body">
                    <p>Вы хотите сохранить изменения в этом документе перед закрытием?</p>
                    <p class="text-secondary"><small>Если вы не сохраните, ваши изменения будут потеряны.</small></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary">Сохранить изменения</button>
                </div>
            </div>
        </div>
    </div>
    <!-- hero slider -->
    <section class="hero-section overlay bg-cover" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">

            {% if form.errors %}
                <div class="col-sm-12">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ field.label }}</strong>: {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.label }}</strong>: {{ error|escape }}
                        </div>
                    {% endfor %}
                </div>
            {% else %}

                <div class="hero-slider-item">
                    <div class="hero-slider">
                        {% for item in all_events %}
                            {% if item.hero_slider %}
                                <!-- slider item -->
                                <div class="row">
                                    <div class="col-md-8">
                                        <h1 class="text-white" data-animation-out="fadeOutRight" data-delay-out="5"
                                            data-duration-in=".3" data-animation-in="fadeInLeft"
                                            data-delay-in=".1">{{ item.title }}</h1>
                                        <p class="text-muted mb-4" data-animation-out="fadeOutRight" data-delay-out="5"
                                           data-duration-in=".3" data-animation-in="fadeInLeft"
                                           data-delay-in=".4">{{ item.description }}</p>
                                        <a href="{{ item.url }}" class="btn btn-primary" data-animation-out="fadeOutRight"
                                           data-delay-out="5" data-duration-in=".3" data-animation-in="fadeInLeft"
                                           data-delay-in=".7">Apply now</a>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

            {% endif %}
        </div>
    </section>
    <!-- /hero slider -->
{% endblock %}

{% block content %}
{% endblock %}

{% block cta %}
    <!-- cta -->
    <section class="section bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <h6 class="text-white font-secondary mb-0">Click to Join the Advance Workshop</h6>
                    <h2 class="section-title text-white">Training In Advannce Networking</h2>
                    <a href="#" class="btn btn-secondary">join now</a>
                </div>
            </div>
        </div>
    </section>
    <!-- /cta -->
{% endblock %}

{% block events %}
    <!-- events -->
    <section class="section bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex align-items-center section-title justify-content-between">
                        <h2 class="mb-0 text-nowrap mr-3">Upcoming Events</h2>
                        <div class="border-top w-100 border-primary d-none d-sm-block"></div>
                        <div>
                            <a href="#" class="btn btn-sm btn-primary-outline ml-sm-3 d-none d-sm-block">see
                                all</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                {% for item in all_events %}
                <!-- event -->
                <div class="col-lg-4 col-sm-6 mb-5 mb-lg-0">
                    <div class="card border-0 rounded-0 hover-shadow">
                        <div class="card-img position-relative">
                            <img class="card-img-top rounded-0" src="{% if item.logo %}{{ item.logo.url }}{% endif %}"
                                 alt="event thumb">
                            <div class="card-date"><span>{{ item.start_time | date:'d' }}</span><br>{{ item.start_time | date:'M' }}</div>
                        </div>
                        <div class="card-body">
                            <!-- location -->
                            <p><i class="ti-location-pin text-primary mr-2"></i>{{ item.location }}</p>
                            <a href="{{ item.url }}"><h4 class="card-title">{{ item.title }}</h4>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- mobile see all button -->
            <div class="row">
                <div class="col-12 text-center">
                    <a href="#" class="btn btn-sm btn-primary-outline d-sm-none d-inline-block">sell all</a>
                </div>
            </div>
        </div>
    </section>
    <!-- /events -->
{% endblock %}
<!-- footer -->
<footer>
    <!-- copyright -->
    <div class="copyright py-4 bg-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-7 text-sm-left text-center">
                    <p class="mb-0">Copyright {% now "Y" %} © <a href="https://tellcap.ru">TELLCAP</a>. All Rights
                        Reserved.
                    </p>
                </div>
                <div class="col-sm-5 text-sm-right text-center">
                    <ul class="list-inline">
                        <li class="list-inline-item"><a class="d-inline-block p-2"
                                                        href="#"><i
                                class="ti-twitter-alt text-primary"></i></a></li>
                        <li class="list-inline-item"><a class="d-inline-block p-2"
                                                        href="#"><i
                                class="ti-dribbble text-primary"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- /footer -->

<!-- Bootstrap JS -->
<script src="{% static 'tutor/plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'tutor/plugins/slick/slick.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'tutor/plugins/aos/aos.js' %}"></script>
<!-- venobox popup -->
<script src="{% static 'tutor/plugins/venobox/venobox.min.js' %}"></script>
<!-- mixitup filter -->
<script src="{% static 'tutor/plugins/mixitup/mixitup.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'tutor/js/script.js' %}"></script>

{% block custom_script %}

{% endblock %}

</body>
</html>

authapp/templates/authapp/customuser_form.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <!-- page title -->
    <section class="page-title-section overlay" data-background="images/backgrounds/page-title.jpg">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'authapp:users_list' %}">Users</a>
                        </li>
                        <li class="list-inline-item text-white h3 font-secondary nasted">{{ object }} details</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- /page title -->

    <!-- event single -->
    <section class="section-sm">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="col-12">
                        <button type="submit" class="btn btn-primary">SAVE</button>
                </div>
            </form>
        </div>
    </section>
    <!-- /event single -->

{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}

authapp/templates/authapp/customuser_list.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <section class="page-title-section overlay" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'authapp:users_list' %}">Users</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- courses -->
    <section class="section-sm">
        <div class="container">

            <!-- course list -->
            <div class="row justify-content-center">
                <table class="table table-striped mb-0" id="datatable-ecommerce-list"
                       style="min-width: 750px;">
                    <thead>
                    <tr>
                        <th width="10%">ID</th>
                        <th width="10%">ФИО</th>
                        <th width="20%">Email</th>
                        <th width="20%">Персонал</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in object_list %}
                        <tr class="clickable-row" data-href="{% url 'authapp:users_update' item.pk %}">
                            <td>{{ item.pk }}</td>
                            <td>{{ item }}</td>
                            <td>{{ item.email }}</td>
                            <td>{{ item.superintendent }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /course list -->
            <!-- mobile see all button -->
            <div class="row">
                <div class="col-12 text-center">
                    <a href="#" class="btn btn-sm btn-primary-outline d-sm-none d-inline-block">sell all</a>
                </div>
            </div>
        </div>
    </section>
    <!-- /courses -->
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

{% block custome_script %}

{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}

authapp/templates/authapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

authapp/templates/authapp/navbar.html
{% load static %}
<div class="navigation w-100">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light p-0">
            <a class="navbar-brand" href="/"><img src="{% static 'tutor/images/logo/logo.png' %}" alt="logo"
                                                  style="width: 96px"></a>
            <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navigation">
                <ul class="navbar-nav ml-auto text-center">
                    <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item @@courses {% if request.path == '/courses/list/' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'courseapp:course_list' %}">COURSES</a>
                    </li>
                    <li class="nav-item @@events {% if request.path == '/courses/events-list/' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'courseapp:events_list' %}">EVENTS</a>
                    </li>
                    <li class="nav-item @@contact">
                        <a class="nav-link" href="#">CONTACT</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown view">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ user }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if user.is_superuser %}
                                    <a class="dropdown-item" href="/admin/">Admin panel</a>
                                {% endif %}
                                <a class="dropdown-item" href="#">Profile</a>
                                <a class="dropdown-item" href="#">Balance</a>
                                <a class="dropdown-item" href="{% url 'authapp:logout' %}">Exit</a>
                            </div>
                        </li>
                    {% endif %}
                    {% if user.is_superuser %}
                        <li class="nav-item dropdown view">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Настройки
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'authapp:users_list' %}">Users</a>
                                <a class="dropdown-item" href="{% url 'courseapp:course_settings_list' %}">Course</a>
                                <a class="dropdown-item" href="{% url 'courseapp:relation_settings_list' %}">Relation</a>
                                <a class="dropdown-item" href="{% url 'courseapp:events_settings_list' %}">Events</a>
                                <a class="dropdown-item" href="#">Unit</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
</div>

authapp/templates/authapp/top_header.html
<div class="top-header py-2 bg-white">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-lg-4 text-center text-lg-left">
                <a class="text-color mr-3" href="callto:+74955891356"><strong>Call</strong> +7 (495) 589-13-56</a>
                <ul class="list-inline d-inline">
                    <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i
                            class="ti-twitter-alt"></i></a></li>
                    <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i
                            class="ti-linkedin"></i></a></li>
                </ul>
            </div>
            <div class="col-lg-8 text-center text-lg-right">
                <ul class="list-inline">
                    <li class="list-inline-item"><a
                            class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                            href="#">Notice</a></li>
                    <li class="list-inline-item"><a
                            class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                            href="#">Research</a></li>
                    <li class="list-inline-item"><a
                            class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                            href="#">Scholarship</a></li>
                    {% if not user.is_authenticated %}
                        <li class="list-inline-item"><a
                                class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                                href="#" data-toggle="modal" data-target="#loginModal">Login</a>
                        </li>
                        <li class="list-inline-item"><a
                                class="reg text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                                href="#" data-toggle="modal" data-target="#signupModal">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>