authapp/urls.py
from django.urls import path

import authapp.views

app_name = 'authapp'

urlpatterns = [
    path('', authapp.views.index, name='index'),
    path('login/', authapp.views.login, name='login'),
    path('logout/', authapp.views.logout, name='logout'),
    path('register/', authapp.views.registration, name='register'),
    path('list/', authapp.views.CustomUserList.as_view(), name='users_list'),
    path('update/<int:pk>/', authapp.views.CustomUserUpdate.as_view(), name='users_update'),
]

courseapp/urls.py
from django.urls import path

import courseapp.views

app_name = 'courseapp'

urlpatterns = [
    # path('', authapp.views.index, name='index'),
    path('list/', courseapp.views.CourseList.as_view(), name='course_list'),
    path('settings/', courseapp.views.CourseSettingsList.as_view(), name='course_settings_list'),
    path('add/', courseapp.views.CourseAdd.as_view(), name='course_add'),
    path('<int:pk>/', courseapp.views.CourseItem.as_view(), name='course'),
    path('update/<int:pk>/', courseapp.views.CourseUpdate.as_view(), name='course_update'),
    # path('logout/', authapp.views.logout, name='logout'),
    path('events-list/', courseapp.views.SiteEventsList.as_view(), name='events_list'),
    path('events-settings-list/', courseapp.views.SiteEventsSettingsList.as_view(), name='events_settings_list'),
    path('events/<int:pk>/', courseapp.views.SiteEventsItem.as_view(), name='events'),
    path('events/add/', courseapp.views.SiteEventsAdd.as_view(), name='events_add'),
    path('events/update/<int:pk>/', courseapp.views.SiteEventsUpdate.as_view(), name='events_update'),
    path('relation-settings-list/', courseapp.views.RelationSettingsList.as_view(), name='relation_settings_list'),
]

tutorTellcap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import authapp.views

handler404 = authapp.views.show_404

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', authapp.views.index),
    path('auth/', include('authapp.urls')),
    path('courses/', include('courseapp.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courseapp/models.py
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field
from django.db import models
from django.utils import timezone

from authapp.models import CustomUser


# Create your models here.

def course_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return f'course/{filename}'

def events_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return f'events/{filename}'


class GoogleForm(models.Model):
    class Meta:
        verbose_name = 'Google форма'
        verbose_name_plural = 'Google формы'

    name = models.CharField(verbose_name='Название', max_length=500, default='GoogleForm')
    url = models.URLField(verbose_name='Ссылка')
    width = models.CharField(verbose_name='Ширина в процентах', max_length=3, default='100')
    height = models.CharField(verbose_name='Высота в процентах', max_length=3, default='100')

    def __str__(self):
        return self.name


class BaseModule(models.Model):
    class Meta:
        abstract = True
    uin = models.CharField(verbose_name='УИН', max_length=37, default=uuid.uuid4)
    name = models.CharField(verbose_name='Название', max_length=100)
    logo = models.ImageField(verbose_name='Логотип', upload_to=course_directory_path, blank=True)
    date_created = models.DateField(verbose_name='Дата создания', default=timezone.now)
    short_description = models.CharField(verbose_name='Краткое описание', max_length=120, blank=True)
    content = CKEditor5Field('Text', config_name='extends', default='', blank=True)


class Course(BaseModule):
    choise_time = [
        ('0', 'Min'),
        ('1', 'Hours'),
        ('2', 'Month'),
        ('3', 'Year'),
    ]

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    courses = models.BigIntegerField(verbose_name='Общее время', default=0)
    courses_time = models.CharField(verbose_name='Измерение курса', choices=choise_time, help_text='',
                                    blank=True, default='', max_length=5)
    duration = models.BigIntegerField(verbose_name='Продолжительность', default=0)
    duration_time = models.CharField(verbose_name='Измерение продолжительности', choices=choise_time, help_text='',
                                     blank=True, default='', max_length=5)
    cost = models.FloatField(verbose_name='Стоимость', default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('courseapp:course_settings_list')



class RelatedCourse(models.Model):
    class Meta:
        verbose_name = 'Связанные курсы'
        verbose_name_plural = 'Связанные курсы'

    from_course = models.ForeignKey(Course, related_name='course_with', on_delete=models.SET_NULL, null=True,
                                    blank=True)
    to_course = models.ManyToManyField(Course, related_name='related_courses')

    def get_absolute_url(self):
        return reverse('courseapp:relation_settings_list')


class CourseModule(BaseModule):
    class Meta:
        verbose_name = 'Модуль'
        verbose_name_plural = 'Модули'

    parent_course = models.ForeignKey(Course, verbose_name='Курс', on_delete=models.SET_NULL, null=True, blank=True)


class SiteEvents(models.Model):
    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    title = models.CharField(verbose_name='Заголовок', max_length=100, default='')
    description = models.CharField(verbose_name='Описание', max_length=350, default='')
    location = models.CharField(verbose_name='Место проведения', max_length=100, default='')
    logo = models.ImageField(verbose_name='Логотип', upload_to=events_directory_path, blank=True)
    start_time = models.DateField(verbose_name='Начало события', default=timezone.now)
    end_time = models.DateField(verbose_name='Окончание события', default=timezone.now)
    content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True, blank=True)
    url = models.CharField(verbose_name='Ссылка', max_length=300, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    hero_slider = models.BooleanField(verbose_name='Отображать на слайдере', default=False)
    speaker = models.ManyToManyField(CustomUser)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courseapp:events_list')

@receiver(post_save, sender=SiteEvents)
def change_url(sender, instance, **kwargs):
    try:
        # Формируем URL
        if instance.content_type.model == 'course':
            if instance.url != f'/courses/{instance.object_id}/':
                instance.url = f'/courses/{instance.object_id}/'
                instance.save()
    except Exception as _ex:
        pass
        #logger.error(f'Ошибка при переименовании файла {_ex}')

courseapp/forms.py
from django import forms
from django_ckeditor_5.fields import CKEditor5Field
from django_ckeditor_5.widgets import CKEditor5Widget

from courseapp.models import Course, SiteEvents


class CourseAddForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ('name', 'logo', 'date_created', 'short_description', 'content', 'courses', 'courses_time', 'duration', 'duration_time', 'cost')
        widgets = {
            "content": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="extends"
            )
        }

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form form-control', 'autocomplete': 'off'})

        self.fields['content'].widget.attrs.update({'class': 'form-control django_ckeditor_5'})
        self.fields['content'].required = False


class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('name', 'logo', 'date_created', 'short_description', 'content', 'courses', 'courses_time', 'duration', 'duration_time', 'cost')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form form-control mb-3'})



class SiteEventsAddForm(forms.ModelForm):

    class Meta:
        model = SiteEvents
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form form-control mb-3'})


class SiteEventsUpdateForm(forms.ModelForm):

    class Meta:
        model = SiteEvents
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form form-control mb-3'})

courseapp/views.py
from django.http import JsonResponse
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from courseapp.forms import CourseAddForm, CourseUpdateForm, SiteEventsAddForm, SiteEventsUpdateForm
from courseapp.models import Course, RelatedCourse, GoogleForm, SiteEvents
from re import sub as google_form


# Create your views here.

class CourseList(ListView):
    model = Course


class CourseSettingsList(ListView):
    model = Course
    template_name = 'courseapp/course_settings_list.html'

    def get(self, request, *args, **kwargs):
        # Определяем, пришел ли запрос как JSON? Если да, то возвращаем JSON ответ
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            course_list = Course.objects.all()
            data = [course_item.get_data() for course_item in course_list]
            response = {'data': data}
            print(response)
            return JsonResponse(response)
        return super().get(request, *args, **kwargs)


class CourseAdd(CreateView):
    model = Course
    form_class = CourseAddForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_absolute_url(self):
        return reverse('courseapp:course_list')


def get_google_form(pattern):
    try:
        obj = GoogleForm.objects.get(name=pattern.group(0))
        url = f'<iframe src="{obj.url}" width="{obj.width}%" height="{obj.height}" seamless="seamless" frameborder="0" marginwidth="0" marginheight="0" html="Загрузка..."></iframe>'
    except Exception as _ex:
        return pattern.group(0)
    return url


def get_audio_file(pattern):
    try:
        url = f'<audio controls="controls" crossorigin="anonymous" style="width:100%;" controlsList="nodownload"><source src="/media/{pattern.group(0)}" type="audio/mpeg"></audio>'
    except Exception as _ex:
        return pattern.group(0)
    return url


class CourseItem(DetailView):
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_object = self.get_object()
        context['title'] = course_object
        content_text = course_object.content
        content_text = google_form(r'(GoogleForm\d+)', get_google_form, content_text)
        context['replase_content'] = content_text
        try:
            related_course = RelatedCourse.objects.get(from_course=course_object)
            context['related_course'] = related_course.to_course.all()

        except Exception as _ex:
            pass

        return context


class CourseUpdate(UpdateView):
    model = Course
    form_class = CourseUpdateForm


class SiteEventsList(ListView):
    model = SiteEvents


class SiteEventsSettingsList(ListView):
    model = SiteEvents
    template_name = 'courseapp/siteevents_settings_list.html'


class SiteEventsItem(DetailView):
    model = SiteEvents


class SiteEventsAdd(CreateView):
    model = SiteEvents
    form_class = SiteEventsAddForm


class SiteEventsUpdate(UpdateView):
    model = SiteEvents
    form_class = SiteEventsUpdateForm


class RelationSettingsList(ListView):
    model = RelatedCourse

courseapp/templates/courseapp/course_detail.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <!-- page title -->
    <section class="page-title-section overlay" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'courseapp:course_list' %}">Our Courses</a></li>
                        <li class="list-inline-item text-white h3 font-secondary nasted">{{ object.name }}</li>
                    </ul>
                    <p class="text-lighten">{{ object.short_description }}</p>
                </div>
            </div>
        </div>
    </section>
    <!-- /page title -->

    <!-- section -->
    <section class="section-sm">
        <div class="container">
            {#    <div class="row">#}
            {#      <div class="col-12 mb-4">#}
            {#        <!-- course thumb -->#}
            {#        <img src="{{ object.logo.url }}" class="img-fluid h-75">#}
            {#      </div>#}
            {#    </div>#}
            <!-- course info -->
            <div class="row align-items-center mb-5">
                <div class="col-xl-3 order-1 col-sm-6 mb-4 mb-xl-0">
                    <h2>{{ object.name }}</h2>
                </div>
                <div class="col-xl-6 order-sm-3 order-xl-2 col-12 order-2">
                    <ul class="list-inline text-xl-center">
                        <li class="list-inline-item mr-4 mb-3 mb-sm-0">
                            <div class="d-flex align-items-center">
                                <i class="ti-book text-primary icon-md mr-2"></i>
                                <div class="text-left">
                                    <h6 class="mb-0">&nbsp;COURSES</h6>
                                    <p class="mb-0">&nbsp;{{ object.courses }} {{ object.get_courses_time_display }}</p>
                                </div>
                            </div>
                        </li>
                        <li class="list-inline-item mr-4 mb-3 mb-sm-0">
                            <div class="d-flex align-items-center">
                                <i class="ti-alarm-clock text-primary icon-md mr-2"></i>
                                <div class="text-left">
                                    <h6 class="mb-0">&nbsp;DURATION</h6>
                                    <p class="mb-0">
                                        &nbsp;{{ object.duration }} {{ object.get_duration_time_display }}</p>
                                </div>
                            </div>
                        </li>
                        <li class="list-inline-item mr-4 mb-3 mb-sm-0">
                            <div class="d-flex align-items-center">
                                <i class="ti-wallet text-primary icon-md mr-2"></i>
                                <div class="text-left">
                                    <h6 class="mb-0">&nbsp;FEE</h6>
                                    <p class="mb-0">&nbsp;From: {{ object.cost }} ₽</p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-xl-3 text-sm-right text-left order-sm-2 order-3 order-xl-3 col-sm-6 mb-4 mb-xl-0">
                    <a href="#" class="btn btn-primary">Apply now</a>
                </div>
                <!-- border -->
                <div class="col-12 mt-4 order-4">
                    <div class="border-bottom border-primary"></div>
                </div>
            </div>
            <!-- course details -->
            <div class="row">
                <div class="col-12 mb-4">
                    {{ replase_content | safe }}
                </div>
            </div>
        </div>
    </section>
    <!-- /section -->

    <!-- related course -->
    {% if related_course %}
        <section class="section pt-0">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2 class="section-title">Related Course</h2>
                    </div>
                </div>
                <div class="row justify-content-center">
                    {% for item in related_course %}
                        <!-- course item -->
                        <div class="col-lg-4 col-sm-6 mb-5">
                            <div class="card p-0 border-primary rounded-0 hover-shadow">
                                {% if item.logo %}
                                    <img class="card-img-top rounded-0" src="{{ item.logo.url }}"
                                         alt="course thumb">
                                {% endif %}
                                <div class="card-body">
                                    <ul class="list-inline mb-2">
                                        <li class="list-inline-item"><i
                                                class="ti-calendar mr-1 text-color"></i>{{ item.date_created }}
                                        </li>

                                    </ul>
                                    <a href="{% url 'courseapp:course' item.pk %}">
                                        <h4 class="card-title">{{ item.name }}</h4>
                                    </a>
                                    <p class="card-text mb-4"> {{ item.short_description }}</p>
                                    <a href="{% url 'courseapp:course' item.pk %}" class="btn btn-primary btn-sm">Apply
                                        now</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}
    <!-- /related course -->
{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}

courseapp/templates/courseapp/course_settings_list.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <section class="page-title-section overlay" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'courseapp:course_list' %}">Our Courses</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- courses -->
    <section class="section-sm">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex align-items-center section-title justify-content-between">
                        <div class="col-12 col-lg-auto mb-3 mb-lg-0">
                            <a href="{% url 'courseapp:course_add' %} "
                               class="btn btn-danger btn-md font-weight-semibold btn-py-2 px-4">+
                                Добавить курс </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- course list -->
            <div class="row justify-content-center">
                <table class="table table-striped mb-0" id="datatable-ecommerce-list"
                       style="min-width: 750px;">
                    <thead>
                    <tr>
                        <th width="10%">Наименование</th>
                        <th width="10%">Общее время</th>
                        <th width="20%">Описание</th>
                        <th width="20%">Цена</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in object_list %}
                        <tr class="clickable-row" data-href="{% url 'courseapp:course' item.pk %}">
                            <td>{{ item.name }}</td>
                            <td>{{ item.courses }} {{ item.get_courses_time_display }}</td>
                            <td>{{ item.short_description }}</td>
                            <td>{{ item.cost }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /course list -->
            <!-- mobile see all button -->
            <div class="row">
                <div class="col-12 text-center">
                    <a href="#" class="btn btn-sm btn-primary-outline d-sm-none d-inline-block">sell all</a>
                </div>
            </div>
        </div>
    </section>
    <!-- /courses -->
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

{% block custome_script %}

{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}

courseapp/templates/courseapp/relatedcourse_list.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <section class="page-title-section overlay" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'courseapp:relation_settings_list' %}">Relation List</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- courses -->
    <section class="section-sm">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex align-items-center section-title justify-content-between">
                        <div class="col-12 col-lg-auto mb-3 mb-lg-0">
                            <a href="{% url 'courseapp:course_add' %} "
                               class="btn btn-danger btn-md font-weight-semibold btn-py-2 px-4">+
                                Добавить связь </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- course list -->
            <div class="row justify-content-center">
                <table class="table table-striped mb-0" id="datatable-ecommerce-list"
                       style="min-width: 750px;">
                    <thead>
                    <tr>
                        <th width="10%">Наименование</th>
                        <th width="10%">Общее время</th>
                        <th width="20%">Описание</th>
                        <th width="20%">Цена</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in object_list %}
                        <tr class="clickable-row" data-href="{% url 'courseapp:course' item.pk %}">
                            <td>{{ item.name }}</td>
                            <td>{{ item.courses }} {{ item.get_courses_time_display }}</td>
                            <td>{{ item.short_description }}</td>
                            <td>{{ item.cost }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /course list -->
            <!-- mobile see all button -->
            <div class="row">
                <div class="col-12 text-center">
                    <a href="#" class="btn btn-sm btn-primary-outline d-sm-none d-inline-block">sell all</a>
                </div>
            </div>
        </div>
    </section>
    <!-- /courses -->
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

{% block custome_script %}

{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}

courseapp/templates/courseapp/siteevents_list.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <section class="page-title-section overlay" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'courseapp:events_list' %}">Upcoming Events</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- courses -->
<section class="section">
  <div class="container">
    <div class="row">
      <!-- event -->
        {% for item in all_events %}
      <div class="col-lg-4 col-sm-6 mb-5">
        <div class="card border-0 rounded-0 hover-shadow">
          <div class="card-img position-relative">
            <img class="card-img-top rounded-0" src="{% if item.logo %}{{ item.logo.url }}{% endif %}" alt="event thumb">
            <div class="card-date"><span>{{ item.start_time | date:'d' }}</span><br>{{ item.start_time | date:'M' }}</div>
          </div>
          <div class="card-body">
            <!-- location -->
            <p><i class="ti-location-pin text-primary mr-2"></i>{{ item.location }}</p>
            <a href="{% url 'courseapp:events' item.pk %}">
              <h4 class="card-title">{{ item.title }}</h4>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- /courses -->
{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}

courseapp/templates/courseapp/siteevents_settings_list.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block slider %}
{% endblock %}

{% block content %}
    <section class="page-title-section overlay" data-background="{% static 'tutor/images/background/00000.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary"
                                                        href="{% url 'courseapp:course_list' %}">Our Courses</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- courses -->
    <section class="section-sm">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex align-items-center section-title justify-content-between">
                        <div class="col-12 col-lg-auto mb-3 mb-lg-0">
                            <a href="{% url 'courseapp:events_add' %} "
                               class="btn btn-danger btn-md font-weight-semibold btn-py-2 px-4">+
                                Добавить событие </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- course list -->
            <div class="row justify-content-center">
                <table class="table table-striped mb-0" id="datatable-ecommerce-list"
                       style="min-width: 750px;">
                    <thead>
                    <tr>
                        <th width="20%">Наименование</th>
                        <th width="30%">Описание</th>
                        <th width="15%">Старт</th>
                        <th width="15%">Стоп</th>
                        <th width="20%">Связь</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in object_list %}
                        <tr class="clickable-row" data-href="{% url 'courseapp:events' item.pk %}">
                            <td>{{ item.title }}</td>
                            <td>{{ item.description }}</td>
                            <td>{{ item.start_time }}</td>
                            <td>{{ item.end_time }}</td>
                            <td>{{ item.content_object }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /course list -->
            <!-- mobile see all button -->
            <div class="row">
                <div class="col-12 text-center">
                    <a href="#" class="btn btn-sm btn-primary-outline d-sm-none d-inline-block">sell all</a>
                </div>
            </div>
        </div>
    </section>
    <!-- /courses -->
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

{% block custome_script %}

{% endblock %}

{% block cta %}
{% endblock %}

{% block events %}
{% endblock %}